### ISSUE TITLE
Resizing Persistent Volumes

### ISSUE THREAD

**Issue by pehbehbeh** [digitalocean/csi-digitalocean#106]
### What did you do?

I created a persistent volume claim:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: u-xxx
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
  creationTimestamp: 2018-11-19T17:11:59Z
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: mypvc
  namespace: mynamespace
  resourceVersion: "xxx"
  selfLink: /api/v1/namespaces/mynamespace/persistentvolumeclaims/mypvc
  uid: xxx
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 8Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem
  volumeName: pvc-xxx
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
```

I tried to resize the persistent volume claim as described [here](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/).

```
spec:
  ...
  resources:
    requests:
      storage: 12Gi
  ...
```

But I got the following error:

```
> kubectl edit pvc mypvc -n mynamespace
error: persistentvolumeclaims "mypvc" could not be patched: persistentvolumeclaims "mypvc" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

### What did you expect to happen?

I wanted to expand the existing volume.

### Configuration

* CSI Version:
  * `quay.io/k8scsi/csi-provisioner:v0.4.1`
  * `digitalocean/do-csi-plugin:v0.3.1`
  * `quay.io/k8scsi/csi-attacher:v0.4.1`

* Kubernetes Version: `v1.12.1`

* Cloud provider/framework version, if applicable (such as Rancher):
  * cluster created via DigitalOcean Kubernetes Beta
  * managed via another Rancher 2.1.1 instance (imported cluster)

**Comment by devfelipereis** [comment]
My sample app was using 2Gb and now I'm trying to use 5Gb. 

I can resize via DO but the app will not reconize that 5Gb and will throw an error that it is out of space.

**Comment by kjellberg** [comment]
I'm having the same problem. Any solutions on this yet?

**Comment by fatih** [comment]
Resizing is not yet supported, we're waiting for the new sidecar `external-resizer`, which is not yet implemented: https://github.com/kubernetes-csi/external-resizer This will be a part of the controller once released and we'll make sure to implement it in a proper way. Until then, I wouldn't suggest to resize as it would break the various states in Kubernetes.

**Comment by Berndinox** [comment]
+1
plz notify if this is finished / possible.

**Comment by botzill** [comment]
Yes, this is a must feature thx.

**Comment by boedy** [comment]
Is there any workaround that allows to upgrade the volume without having to destroy and recreate the k8s workloads?

**Comment by joeycumines** [comment]
I still had to schedule downtime so it doesn't address @boedy 's request (although I can't remember if it was 100% necessary), but it is possible to resize a volume manually even though it isn't supported @pehbehbeh @devfelipereis @timoreimann @fatih @Berndinox @botzill 

The CSI spec does now support this feature since https://github.com/container-storage-interface/spec/pull/334 which was released v1.1.0 or something (don't quote me on that lol). I find it a bit shocking this still isn't available as a supported feature.

DISCLAIMER if you aren't prepared to accidentally nuke your data you probably shouldn't be attempting this, and it could break future implementations of this as an actual feature.

Manual instructions (a lot of this is from memory, so your mileage may vary):

1. Determine the pvc that you need to resize, and check the available size within the pod / container which is using it by exec'ing `df -h`
2. Match the id vs what you see in DO, and resize the relevant volume using their GUI (or their API), I think I had it unmounted at the time (by destroying the deployment / pod that had it attached)
3. Remount the pvc by recreating the pod with the volume that has the volume you want to resize, if you deleted it to perform step 2 (unmounting while resizing could be necessary idk DO gave me an error the first time around so I just nuked it lol)
4. Check what _pods_ are running on what _nodes_ (droplets in DO land) using `kubectl describe nodes` or the k8s dashboard app
5. Determine which node the pod with the volume you want to resize is running on
6. Determine the name of the _pod_ prefixed with `csi-do-node-` in the `kube-system` namespace, on the same node as the **running** pod with the **mounted** volume
7. Exec into the `csi-do-plugin` container of the pod you found in step 6, the actual command will be something like `kubectl --namespace kube-system exec -c csi-do-plugin -it csi-do-node-9lhhm sh`, which will exec you into a shell
8. The image seems to be based on alpine linux, and you want to 
follow https://www.digitalocean.com/docs/volumes/how-to/increase-size/ and you need some utils, so run `apk update && apk add util-linux`
9. Run `ls -alh /dev/disk/by-id/`, you should see your volume's id as part of the output, as something along the lines of `scsi-0DO_Volume_pvc-20613b61-3d8a-11e9-b2a8-d6463c43705b`
10. Follow the DO guide I linked in step 8, should be something like `lsblk --fs /dev/disk/by-id/scsi-0DO_Volume_pvc-20613b61-3d8a-11e9-b2a8-d6463c43705b` followed by `resize2fs /dev/disk/by-id/scsi-0DO_Volume_pvc-20613b61-3d8a-11e9-b2a8-d6463c43705b`
11. I don't think it is actually necessary, but I did recreate the deployment after step 10.
12. Check the available size by exec'ing `df -h` within the running pod / container that has the volume mounted, it should have increased from step 1. (you will have to find the pod again if you deleted it or it got recreated at any point since then)

**Comment by adamwg** [comment]
CSI now supports volume expansion. @varshavaradarajan is working on implementing it in #193.

**Comment by dsebastien** [comment]
I'm just starting out with DOKS, so I hope support for this will be added soon, it is clearly a must-have for our production workloads :)

**Comment by timoreimann** [comment]
@dsebastien we're working on this as we speak, so hopefully should be available pretty soon. :)

**Comment by srv-io** [comment]
@timoreimann  With #193 merged, what does block this feature? The lack of PVC resizing is a dealbreaker right now. :(

**Comment by YourTechBud** [comment]
@srv-io the readme suggests PVCs can be resized (only increased). Haven't tried it out yet.

**Comment by timoreimann** [comment]
@srv-io the only thing missing is to cut a release and (for DOKS users) ship it with our next batch of images.

I'm in the process of making this happen right now. Keep an eye on the Github releases and the DOKS change log. I will also post updates here as we progress.

**Comment by timoreimann** [comment]
Downsizing is not supported for now. If there's demand for it, we can consider providing support for that as well. It's a potentially risky operation, however, so we wouldn't want to provide a means that makes it too easy to destroy your data accidentally.

**Comment by timoreimann** [comment]
Like any updates to master, the README updates are referring to the latest development version of our driver. It's recommended to look at tagged commits of the repo to see documentation / files for a particular, released driver version.

**Comment by timoreimann** [comment]
Our newest DOKS version 1.16.2-do.3 has just been shipped and supports volume expansion / resizing. See the [volume feature overview page](https://www.digitalocean.com/docs/kubernetes/resources/volume-features/) for links to usage documentation.
