### ISSUE TITLE
Hard limit of volume mounts total...?

### ISSUE THREAD

**Issue by ptariche** [digitalocean/csi-digitalocean#128]
### What did you do? (required. The issue will be **closed** when not provided.)
I launched 3 nodes ($20 dollar instances with k8 cluster offering from DO). After launching enough pods with persistent volumes utilizing the do storage class the cluster refuses to assign any more volumes, to the next node, but does not complain as it constantly pends for the volume to be mounted, which places the designated pods waiting for volumes in an infinite Pending state.

I have recreated and destroyed the cluster at least 20 times with this issue persisting. A week ago I was running into issues with Cilium crashing and rebooting but that issue looks to have been patched or fixed.  
 
### What did you expect to happen?

Another volume to be attached to one of the nodes.

### Configuration (**MUST** fill this out):

* system logs:

Please provide the following logs:

All three nodes provide the same healthy information.
```
CreationTimestamp:  Thu, 21 Feb 2019 18:11:50 -0800
Taints:             <none>
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 21 Feb 2019 20:27:19 -0800   Thu, 21 Feb 2019 18:11:50 -0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 21 Feb 2019 20:27:19 -0800   Thu, 21 Feb 2019 18:11:50 -0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 21 Feb 2019 20:27:19 -0800   Thu, 21 Feb 2019 18:11:50 -0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 21 Feb 2019 20:27:19 -0800   Thu, 21 Feb 2019 18:12:30 -0800   KubeletReady                 kubelet is posting ready status. AppArmor enabled
```

  beta.kubernetes.io/instance-type: s-2vcpu-4gb
    name: condescending-murdock-ur71
    namespace: ""
      cpu: "2"
      memory: 3939300Ki
      cpu: "2"
      memory: 4041700Ki
      message: kubelet has sufficient memory available
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^a2380757-3648-11e9-8f70-0a58ac14204e
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^d4edd15f-3648-11e9-a701-0a58ac14213c
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^c784eda9-364b-11e9-8f70-0a58ac14204e
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^bf1d6ff2-364c-11e9-a701-0a58ac14213c
      beta.kubernetes.io/instance-type: s-2vcpu-4gb
    name: condescending-murdock-ur79
    namespace: ""
      cpu: "2"
      memory: 3939300Ki
      cpu: "2"
      memory: 4041700Ki
      message: kubelet has sufficient memory available
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^c6ef7a70-364b-11e9-8f70-0a58ac14204e
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^bc56f83c-364c-11e9-a701-0a58ac14213c
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^e5241566-364c-11e9-a701-0a58ac14213c
      beta.kubernetes.io/instance-type: s-2vcpu-4gb
    name: condescending-murdock-ur7z
    namespace: ""
      cpu: "2"
      memory: 3939300Ki
      cpu: "2"
      memory: 4041700Ki
      message: kubelet has sufficient memory available
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
    - names:
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^dc3b17b0-364c-11e9-a701-0a58ac14213c
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^b9d0fb9b-3648-11e9-a701-0a58ac14213c
      name: kubernetes.io/csi/dobs.csi.digitalocean.com^ca89d515-364c-11e9-a701-0a58ac14213c

{
  "name": "condescending-murdock-ur71",
  "cap": {
    "attachable-volumes-csi-dobs.csi.digitalocean.com": "7",
    "cpu": "2",
    "ephemeral-storage": "82535812Ki",
    "hugepages-1Gi": "0",
    "hugepages-2Mi": "0",
    "memory": "4041700Ki",
    "pods": "110"
  }
}
{
  "name": "condescending-murdock-ur79",
  "cap": {
    "attachable-volumes-csi-dobs.csi.digitalocean.com": "7",
    "cpu": "2",
    "ephemeral-storage": "82535812Ki",
    "hugepages-1Gi": "0",
    "hugepages-2Mi": "0",
    "memory": "4041700Ki",
    "pods": "110"
  }
}
{
  "name": "condescending-murdock-ur7z",
  "cap": {
    "attachable-volumes-csi-dobs.csi.digitalocean.com": "7",
    "cpu": "2",
    "ephemeral-storage": "82535812Ki",
    "hugepages-1Gi": "0",
    "hugepages-2Mi": "0",
    "memory": "4041700Ki",
    "pods": "110"
  }

---
Can share gist of dump if needed
---
* CSI Version: 1.0.0

* Kubernetes Version: 1.13.2-do.1

* Cloud provider/framework version, if applicable (such as Rancher): 1.13.2-do.1

**Comment by ptariche** [comment]
<img width="1199" alt="screen shot 2019-02-21 at 9 07 53 pm" src="https://user-images.githubusercontent.com/3300641/53221139-ea560180-361c-11e9-91c3-87f36943125a.png">

**Comment by ptariche** [comment]
There maybe just a control limit on the amount of volumes one can have on their account without reaching out to support at DO.

https://www.digitalocean.com/community/questions/max-amount-of-block-storage-volumes-on-a-digital-ocean-account

If this is the case, I'll close this ticket and leave a note for others going down this rabbit hole to have the proper information to reach out to DO and increase their volume limits.

**Comment by timoreimann** [comment]
Hi @ptariche 👋

You are right, there is a limit with regards to how many volumes can be mounted overall (per team/account) and per droplet. The details are outlined [here](https://www.digitalocean.com/docs/volumes/overview/#limits). You can reach out to the DO support to have your overall limit increased.

Hope this helps.

**Comment by ptariche** [comment]
👍 

There should be some kind of error from the csi driver if other's run into a similar issue with the api's 403 forbidden response.

**Comment by timoreimann** [comment]
@ptariche if you run `kubectl describe pvc` on a pending PVC that's over limit, you should see a message like

```
failed to provision volume with StorageClass "do-block-storage": rpc error: code = ResourceExhausted desc = volume limit (7) has been reached. Current number of volumes: 7. Please contact support.
```

You would also see that message in the general Kubernetes events (`kubectl get events`).

**Comment by justinbarrick** [comment]
Support is unfortunately unable to help with this issue

![image](https://user-images.githubusercontent.com/29671524/77829844-d31bfa00-70e1-11ea-94f0-6111a9a12e38.jpeg)

**Comment by timthelion** [comment]
seems like k8s on digital ocean is pretty much useless then. Either you have such a simple setup that you shouldn't be using k8s in the first place, or you run into hard limits.

**Comment by timoreimann** [comment]
Just to clarify: support can absolutely bump the total number of volumes that can be created _per account_.

What cannot be adjusted is the _per node_ volume limit of 7 (which may change in the future). However, the scheduler takes the limit into account and automatically places pods to nodes that still have capacity (subject to additional constraints that may impact scheduling, such as node affinity).
It is also possible to enable the cluster autoscaler so that new nodes are automatically created when the volumes-per-node budget is exhausted.

**Comment by StarpTech** [comment]
This limitation feels weird and scaling would break our budget. It's good practice to isolate your applications per volume to not affect each other. This is really attractive because DO supports volumes with low capacity (1GB). @timoreimann that's a bit dramatic. You can use multiple apps with a single PV. Another big problem the community tools have to support that flexible configuration.

**Comment by timthelion** [comment]
@StarpTech after studying the issue further, I found that in our use-case this limitation isn't actually a problem. The thing is that using an external file store such as S3 is actually superior to using volumes  *in our usecase* (which is django apps). This is because S3 buckets can be trivially shared across instances unlike the low level concept of a block store. This makes scaling easier than using volumes and there are no limits neither hard nor soft, involved.

That in no way excuses this weird and inexplicable limitation, it's just a thing you might consider if your use-case is similar.

**Comment by adamwg** [comment]
A couple of notes on this limitation from the DO side:

1. We totally understand it's an awkward limitation, and we are working with the Volumes team to see if it can be resolved in the future. The volumes-per-node limit is due to the fact that regardless of whether you're using DOKS or self-managed k8s on DO, these are normal DO volumes attached to normal DO droplets and we're subject to all the limitations of those products. The limit is, unfortunately, not entirely arbitrary; there are various technical reasons for it, and it has been in place since we introduced Volumes in 2016.
2. One workaround is to use Rook or some other software defined storage system within your cluster, using Volumes as the backing storage. You can use a smaller number of large volumes to back Rook, then provision and use as many small volumes as you like within the cluster, as Rook volumes are completely outside the DO volume limits. We have a number of customers using this approach successfully, and there's a [tutorial on our community site](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-ceph-cluster-within-kubernetes-using-rook) explaining how to set it up. Note that since DO Volumes are replicated in the backend, there's no need to have your in-cluster storage system also replicate, although that may still be desirable for availability reasons (i.e., to ensure storage remains available when you lose a node in your cluster or do an upgrade).

**Comment by StarpTech** [comment]
@adamwg Thanks for the statement.

**Comment by bukowa** [comment]
>     2\. and there's a [tutorial on our community site](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-ceph-cluster-within-kubernetes-using-rook)

People in the comments (including the author) claim that it cannot work out of the box.

**Comment by h0jeZvgoxFepBQ2C** [comment]
This bugged us as well and is nearly a gamebreaker for us. On Amazon you can mount 39 volumes - on DO only 7 :(

Could maybe someone also clarify if this limit applies to NFS mounted volumes as well?
We have an NFS server running for ReadWriteMany workflows and it seems that these mounts also counts to the 7 shares per node - even though they are not block storage mounts?
Or am I wrong @adamwg ?

**Comment by adamwg** [comment]
@h0jeZvgoxFepBQ2C The 7-volume limit applies only to DO block storage volumes. NFS volumes should not affected by it.

**Comment by StarpTech** [comment]
@adamwg DO support NFS storage as a service?

**Comment by adamwg** [comment]
@StarpTech No, at this time we do not have a managed NFS product. However, users can configure an NFS server themselves or use a solution like the [OpenEBS NFS provisioner](https://github.com/openebs/dynamic-nfs-provisioner) to manage NFS mounts within a DOKS cluster.

**Comment by StarpTech** [comment]
@adamwg thanks for the hint but this has nothing to do with DO integration. We are looking for a managed solution.

**Comment by h0jeZvgoxFepBQ2C** [comment]
It's still sad that the limit is still 7 volumes per node. Any ETA when this will change? This limit is really a big minus point for DO, since NFS server etc have other problems (remounting in case node is not ready anymore etc).

**Comment by adipascu** [comment]
I've opened this proposal. Vote it up if you want to make them priorities this feature.
https://ideas.digitalocean.com/storage/p/allow-more-than-7-volumes-on-a-droplet

**Comment by jabes** [comment]
This is unfortunately a deal breaker for my company. I'm leaving DO because of this, and I hope someone sees this and resolves this limitation. It's unfortunate because I otherwise love DO.

**Comment by nrukavkov** [comment]
what's the stupid limitations

**Comment by walec51** [comment]
> 1. We totally understand it's an awkward limitation, and we are working with the Volumes team to see if it can be resolved in the future. 

3 years have passed @adamwg ...

**Comment by ku9nov** [comment]
Hello guys,
I've encountered a very similar issue.
We have a created and working cluster where 4 volumes are mounted, 2 volumes per node.
When attempting to deploy an identical cluster after running these commands:
```
kubectl apply -fhttps://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v4.0.0/{crds.yaml,driver.yaml,snapshot-controller.yaml}
kubectl apply -f do-block-storage/test-pvc.yaml
```
I receive the following error:
```
kubectl describe pvc csi-do-pvc
Name:          csi-do-pvc
Namespace:     default
StorageClass:  do-block-storage
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                     From                                                                                Message
  ----     ------                ----                    ----                                                                                -------
  Normal   ExternalProvisioning  3m19s (x26 over 9m31s)  persistentvolume-controller                                                         waiting for a volume to be created, either by external provisioner "dobs.csi.digitalocean.com" or manually created by system administrator
  Normal   Provisioning          51s (x10 over 9m31s)    dobs.csi.digitalocean.com_csi-do-controller-0_a202406b-6db8-4263-975b-29e8efc22c1a  External provisioner is provisioning volume for claim "default/csi-do-pvc"
  Warning  ProvisioningFailed    50s (x10 over 9m30s)    dobs.csi.digitalocean.com_csi-do-controller-0_a202406b-6db8-4263-975b-29e8efc22c1a  failed to provision volume with StorageClass "do-block-storage": rpc error: code = ResourceExhausted desc = volume limit (3) has been reached. Current number of volumes: 4. Please contact support.
```
which is quite strange because you mention here that there should be no more than 7 volumes per node, and we only have 2 volumes per node.
Could you help me understand the issue?
this is test-pvc.yaml content
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-do-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
```

**Comment by gottwald** [comment]
This seems unrelated to the 7 volume limit per droplet. It may be a quota exhaustion on your account. Please contact DO support.
