### ISSUE TITLE
Not able to attach pv to node ( has no NodeID annotation)

### ISSUE THREAD

**Issue by jasondewitt** [digitalocean/csi-digitalocean#132]
### What did you do? (required. The issue will be **closed** when not provided.)
I have been trying to set up the DO csi plugin on my cluster and am running into problems.  I am following the readme, using all the example manifests. Everything appears to install correctly, the storage volume gets created on DO, but it does not attach to the node when I create the test pod.

### What did you expect to happen?
The storage volume would attach to the correct node when the test pod is scheduled

### Configuration (**MUST** fill this out):

create the DO token secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
stringData:
  access-token: "redacted"
```

installed the csi plugin:
`kubectl apply -f https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v1.0.0.yaml`

create the test pvc, volume is created on DO

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
```

Create the test pod

```
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-do-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-do-volume
      persistentVolumeClaim:
        claimName: csi-pvc 
```

Attach to node fails:

```
Events:
  Type     Reason              Age                  From                      Message
  ----     ------              ----                 ----                      -------
  Normal   Scheduled           2m35s                default-scheduler         Successfully assigned default/my-csi-app to kube2.roxet.net
  Warning  FailedAttachVolume  2m20s                attachdetach-controller   AttachVolume.Attach failed for volume "pvc-c836646c-4865-11e9-8923-8eddd06318fa" : attachment timeout for volume cbe431cb-4865-11e9-a56d-0a58ac146e34
  Warning  FailedMount         32s                  kubelet, kube2.roxet.net  Unable to mount volumes for pod "my-csi-app_default(d5f984fd-4865-11e9-8923-8eddd06318fa)": timeout expired waiting for volumes to attach or mount for pod "default"/"my-csi-app". list of unmounted volumes=[my-do-volume]. list of unattached volumes=[my-do-volume default-token-mms2t]
  Warning  FailedAttachVolume  10s (x8 over 2m17s)  attachdetach-controller   AttachVolume.Attach failed for volume "pvc-c836646c-4865-11e9-8923-8eddd06318fa" : node "kube2.roxet.net" has no NodeID annotation
```
System logs:
https://gist.github.com/jasondewitt/3f08db8926b1afc52cfc9be70bc580e1

* CSI Version:
v1.0.0
* Kubernetes Version:

```
~/dev/rke >>> kubectl version --short
Client Version: v1.13.4
Server Version: v1.13.4
```

* Cloud provider/framework version, if applicable (such as Rancher):
cluster created on Digital Ocean droplets, installed with RKE
`rke version v0.1.17`

The NodeID annotation mentioned in the error message is definitely not there, I am not sure at what point that should have been created.

I am concerned about the Mount Propagation stuff I read in the README, I am not sure this is set up correctly and have not been able to find much info about how configure it. There was some discussion in #79 with a link which is, sadly, now dead.
https://github.com/digitalocean/csi-digitalocean/issues/79#issuecomment-421951118

**Comment by beshkenadze** [comment]
We have the same issue, any updates from the team do?

**Comment by rust84** [comment]
We are also having this issue since installing Rancher 2.2.2 today. This was on a brand new install.

> kubectl version --short
Client Version: v1.12.7
Server Version: v1.13.5

**Comment by hoangnguyenasnet** [comment]
I'm facing the same issue too with the same version, any updates?

**Comment by hoangnguyenasnet** [comment]
I resolved issue by launched the node the same zone with the volume.

**Comment by bedue** [comment]
I run into exact the same issue, are there any insights to a solution?

**Comment by chrstnwhlrt** [comment]
Possibly same problem [here](https://github.com/rancher/k3s/issues/926)

**Comment by timoreimann** [comment]
Although rather old, #79 described an issue with the same error message. The underlying problem was a missing kubelet parameter as described in https://github.com/digitalocean/csi-digitalocean/issues/79#issuecomment-421950640.

Is this possibly the same problem? How does Rancher parameterize the kubelet?

We'd also appreciate a quick note if this isn't a matter anymore, in which case we could close the issue. Thanks!

**Comment by UristMcMiner** [comment]
We solved it. The --allow-privileged is, if it works, a rather ugly workaround. 
The real problem is, in RancherOS, the kubelet location is not under /var/lib/kubelet, it's under /opt/rke/var/lib/kubelet, which leads to the Sockets created by Trident not being seen by the kubelet, and therefor prevents the kubelet from registering the driver.

The missing NodeID is a sympton of this, because the registrar in the daemonset can't get the needed information for setting the annotation.

The solution to this is to change the paths in the trident-daemonset.yml to the real location of the kubelet. (Prepend /opt/rke to all paths pointing to the kubelet directory, which is in three bind-mounts, and in one environment variable)

So it is not really a bug, Trident just needs a parameter to set the kubelet path to generate the deployments.

**Comment by timoreimann** [comment]
I'll be closing this issue since we haven't received further input in a while.

Additionally, it looks like this is more a Rancher issue (see also longhorn/longhorn#392), so there's probably not much the CSI driver can do here (other than perhaps adding documentation notes for Rancher).

If people believe that that we can be of help somehow, please post and I'll reopen the ticket.
