### ISSUE TITLE
`make bump-versions` generates broken manifests

### ISSUE THREAD

**Issue by waynr** [digitalocean/csi-digitalocean#174]
A couple weeks ago, I ran the `make bump-version` target to bump the `do-csi-plugin` versions when releasing new patch versions of the plugin.

I expected only the `do-csi-plugin` version to be updated, but instead ended up accidentally updating all `csi` components referenced in the example manifests.

See discussion in:

* #166 <- the PR that added the borked manifest
* #172 <- the issue that brought this problem to our attention
* #173 <- the PR that fixes the borked manifest

This issue is intended to track the need to improve our `bump-version` make target to ensure it only bumps `do-csi-plugin` for future releases.

### Versions and stuff
* CSI Version: v1.1.1` for sure, but probably other versions since I performed similar releases on other branches.

**Comment by fatih** [comment]
Hi @waynr 

That's bad indeed. That scripts create a manifest, but it doesn't mean it's the final correct version. It needs to be tested before deployed. That's why I've added the following line in the Readme:

> Make sure everything looks good.

As you stated, we can change the file to be a template and then only replace the parts we're interested in, which is in our case `do-csi-plugin`.

**Comment by timoreimann** [comment]
This one got fixed by #199 most likely.
