### ISSUE TITLE
Needed changes to work on kubernetes 1.16

### ISSUE THREAD

**Issue by GiGurra** [digitalocean/csi-digitalocean#202]
As this is a possibly breaking change for older kubernetes versions, I think you want to have it posted as an issue before any PR. I had to perform the following changes to the 1.1.2 definition to make it work on my rancher 2.3.2/kub 1.16 cluster (non-managed running on DO).

It looks like `apps/v1beta1` is removed and you now just use `apps/v1`, and StatefulSets require selectors. (see https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis)

The deployment goes fine after these changes and I can mount the volumes into my pods as expected :).

```╰─>$ diff -u csi-digitalocean-v1.1.2.yaml.old csi-digitalocean-v1.1.2.yaml.new
--- csi-digitalocean-v1.1.2.yaml.old	2019-11-05 22:47:41.276550997 +0100
+++ csi-digitalocean-v1.1.2.yaml.new	2019-11-05 22:31:18.831645676 +0100
@@ -117,13 +117,17 @@
 ##############################################
 
 kind: StatefulSet
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 metadata:
   name: csi-do-controller
   namespace: kube-system
 spec:
   serviceName: "csi-do"
   replicas: 1
+  selector:
+    matchLabels:
+      app: csi-do-controller
+      role: csi-do
   template:
     metadata:
       labels:
@@ -340,7 +344,7 @@
 ########################################
 
 kind: DaemonSet
-apiVersion: apps/v1beta2
+apiVersion: apps/v1
 metadata:
   name: csi-do-node
   namespace: kube-system```

**Comment by timoreimann** [comment]
Hi @GiGurra 👋 

We indeed haven't updated the API versions for the affected types yet. Thanks for pointing out!

We should release a new version of CSI in order to provide manifests that do not fail on 1.16 anymore (i.e., what you included in your patch). Right now, [the way we increase the CSI plugin version is coupled to what other manifest changes may go into a release](https://github.com/digitalocean/csi-digitalocean/blob/a31f090a350ed24bce07fbd34ed34ae851625fc6/Makefile#L26-L27), so there's not much to PR at this point. I'll make sure though we switch over to `apps/v1` as we go for the next release. (We have one or two PRs pending at the moment that we should get in as well.)

I'll keep the issue open until that new release is out.

Thanks again!

**Comment by timoreimann** [comment]
The new v1.2.0 updated the API version to `apps/v1`.
