### ISSUE TITLE
strange log from stateful pod

### ISSUE THREAD

**Issue by naarani** [digitalocean/csi-digitalocean#84]
### What did you do? (required. The issue will be **closed** when not provided.)
I was just testing some installation on DO + K8s
2 worker with 8 giga ram and an elasticsearch cluster with blockstorage
after some day I stressed the cluster and elasticsearch get out of controll

### What did you expect to happen?
i thought the stateful pod could crash and restart, but not asking to format the blockstorage

there is a limit on blockstorage mapped to nodes? maybe i mapped more then a disk and this crashed the do plugin for storage? .. I'm sure I've done something wrong installing it..

### Configuration (**MUST** fill this out):

* system logs:
MountVolume.MountDevice failed for volume "pvc-2601e322bb2611e8" : rpc error: code = Internal desc = formatting disk failed: exit status 1 cmd: 'mkfs.ext4 -F /dev/disk/by-id/scsi-0DO_Volume_pvc-2601e322bb2611e8' output: "mke2fs 1.43.7 (16-Oct-2017)\nThe file /dev/disk/by-id/scsi-0DO_Volume_pvc-2601e322bb2611e8 does not exist and no size was specified.\n"
Readiness probe failed: Get http://10.2.2.151:9200/_cluster/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Please provide the following logs:

kubectl cluster-info dump > kubernetes-dump.log
ahem.. to many GIGA...

This will output everthing from your cluster.  Please use a private gist via
https://gist.github.com/ to share this dump with us

* CSI Version:
0.20

* Kubernetes Version:
1.10

* Cloud provider/framework version, if applicable (such as Rancher):
installed via typhoon then added csi-digitalocean

**Comment by fatih** [comment]
Hi @naarani 

Which patch version do you use for Kubernetes? Is it plain `v1.10.0` or something else? Our recommended minimum version is `v1.10.5` due the many bug fixes and improvements that were introduced later.  It seems like the block storage was deleted and the pod was scheduled to a new node, where a new volume would be expected, but couldn't be found (hence the error `does not exist and no size was specified`). This error happens if there is no attached volume on the node and the node plugin tries to format & mount it. It doesn't format it if it's already formatted before (because we check it before `blkid`). 

If you can post any manifest and ways to reproduce it (for versions equal or larger than `v1.10.5`) I can try to debug it. Or feel free to send me your kubeconfig if you're ok with it (email: fatih at digitalocean dot com).

**Comment by naarani** [comment]
Actually in production we save data on a share via NFS, and we use block storage only on testing nodes.

On testing nodes we've v1.10.0, I'll need to upgrade it, install 1.11.0 or 1.12.0:
however I'm in the queue of digitalocean to test K8s :-) waiting for an invite, so I think I will move to the next version when we'll test do k8s, thx
